### ISSUE TITLE
Is there anything for a quick start?

### ISSUE THREAD

**Issue by bigreybear** [skejserjensen/ModelarDB#3]
I am a practitioner of TSMS, and really appreciate it if there is any documents or guides for a quick start.

**Comment by skejserjensen** [comment]
The JVM-based version of ModelarDB was developed to determine how storing time series as models (i.e. functions) impacts the design and performance of a TSMS and the results are primarily disseminated through [papers](https://github.com/skejserjensen/ModelarDB#papers) and [presentations](https://github.com/skejserjensen/ModelarDB#presentations). Thus, documenting how to use the system was unfortunately never a priority. However, a very small [user manual](https://github.com/ModelarData/ModelarDB/blob/master/docs/index.md) has been written for the other partners in the [MORE project](https://www.more2020.eu/). Some of the [newer features](https://github.com/ModelarData/ModelarDB/blob/master/CHANGELOG.md), such as the Apache Arrow Flight query interface and how to continuously transfer segments from the edge to the cloud, are unfortunately not documented in the user manual and the Docker image is no longer available, but it is unfortunately, the only information we have created specifically about how to use the system. 

We are currently in the process of implementing a new version of ModelarDB which is designed to be useable for end users. This version is implemented in [Rust](https://www.rust-lang.org/)  and currently uses [Apache Arrow Flight](https://github.com/apache/arrow-rs/tree/master/arrow-flight) for communicating with clients, [Apache Arrow DataFusion](https://github.com/apache/arrow-datafusion) as its query engine, [Apache Arrow](https://github.com/apache/arrow-rs) as its in-memory data format, and [Apache Parquet](https://github.com/apache/arrow-rs/tree/master/parquet) as its on-disk data format. However, while this version incorporates all of the lessons we learned while developing the JVM-based version and the preliminary results are very promising, it is still not ready for production use.

**Comment by bigreybear** [comment]
Thansk for your detailed information, helped me a lot.

**Comment by skejserjensen** [comment]
I forgot to include a link to the repository for the new [Rust-based version of ModelarDB](https://github.com/ModelarData/ModelarDB-RS). It is being developed as an source-code project under [Apache License 2.0](https://github.com/ModelarData/ModelarDB-RS/blob/master/LICENSE).
